### PR TITLE
fix: do not log errors that are rethrown

### LINKED ISSUE #106: Should this library log errors even when they're re-thrown?
In the past weeks, when working with this library, I noticed that a lot of errors are practically logged twice - once by this library, once by the consumer code using it. I'd suggest to either not log errors at all, or provide an option to the `OneDrive` constructor that allows me to suppress logging for errors that are re-thrown.

### PR DESCRIPTION
**Pull request by dominique-pfister**
fix #106

### CODE REVIEW

File: test/decrypt.js [hunk 1]
```diff
@@ -9,6 +9,9 @@
  * OF ANY KIND, either express or implied. See the License for the specific language
  * governing permissions and limitations under the License.
  */
+
+/* eslint-disable no-console */
+
```
Comment (dominique-pfister) [inline test/decrypt.js:14]: logs only warnings in `eslint` but still...

File: src/OneDrive.js [hunk 2]
```diff
@@ -137,11 +137,6 @@ export class OneDrive {
         } catch {
           err = new StatusCodeError(text, resp.status);
         }
-        if (err.statusCode === 404) {
-          this.log.warn(`${relUrl} : ${err.statusCode} - ${err.message}`);
-        } else {
-          this.log.error(`${relUrl} : ${err.statusCode} - ${err.message}`, err.details);
-        }
         throw err;
```
Comment (dominique-pfister) [inline src/OneDrive.js:140]: as the PR title says...
