### PR TITLE
fix: not finding a cached entry should not log a warning

### LINKED ISSUE #119: reduce log level of non existent token cache entry
**Description**
```
Warn: Unable to acquire token from cache: Error: Entry not found in cache.
```

should not be a warning.

### PR DESCRIPTION
**Pull request by dominique-pfister**
fix #119 

for the record: this message is thrown in https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/023fb2e3913e522091368c58d473b0042e6d0c74/lib/token-request.js#L526

### CODE REVIEW

File: src/OneDrive.js [hunk 1]
```diff
@@ -166,7 +166,9 @@ class OneDrive extends EventEmitter {
     try {
       return await context.acquireToken(AZ_RESOURCE, this.username, this.clientId);
     } catch (e) {
-      log.warn(`Unable to acquire token from cache: ${e}`);
+      if (e.message !== 'Entry not found in cache.') {
+        log.warn(`Unable to acquire token from cache: ${e}`);
+      }
```
Comment (tripodsan) [inline src/OneDrive.js:171]:
```suggestion
      } else {
        log.info(`Unable to acquire token from cache: ${e}`);
      }
```
